### ISSUE TITLE
Histomics UI not submitting jobs properly

### ISSUE THREAD

**Issue by btsherid** [DigitalSlideArchive/digital_slide_archive#132]
Hi,

I'm hoping to get some help troubleshooting why our HistomicsUI can't submit a job successfully. I have an image file that I'm trying to run a Positive Pixel Count analysis on. I set up the region and when I click submit I get Connection reset by peer (output below).

I have tested that the dsa_worker_1 container can successfully spawn another docker container by running <code>docker container run dsarchive/histomicstk@sha256:0f741c3a981ddbc31281ccc13f0528879ca20c1e9bc733d97e5a85b0504c031c PositivePixelCount --maxRegionSize 5000 --num_threads_per_worker 1 --num_workers 1 --region "18487, 4424, 1105, 1984" --scheduler "" --tileGrouping 256 --returnparameterfile "<girder_worker.docker.transforms.VolumePath: \"Positive Pixel Count-returnparameterfile\">" "<girder_worker.docker.transforms.girder.GirderFileIdToVolume: File ID=5f369c8f07382a60fada60e0 -> \"PGEM1179.svs\">" .83 .15 .05 .95 .65 .35 .05 </code> from inside the dsa_worker_1 container. That command still fails for other reasons but I can see a new docker container spin up when I run that command.

I do not see a new docker container get created when I click the submit button.

Any help would be appreciated.

Thank You,
Brendan Sheridan

<pre>
[2021-02-19 21:33:26,244: ERROR/ForkPoolWorker-2] Signal handler <function gw_task_prerun at 0x7fe4541dbc20> raised: ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1369, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 271, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 410, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1369, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 271, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python3.7/site-packages/girder_worker/app.py", line 124, in gw_task_prerun
    _update_status(task, JobStatus.RUNNING)
  File "/usr/local/lib/python3.7/site-packages/girder_worker/utils.py", line 88, in _update_status
    task.job_manager.updateStatus(status)
  File "/usr/local/lib/python3.7/site-packages/girder_worker/utils.py", line 280, in updateStatus
    data={'status': status}, allow_redirects=True)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
[2021-02-19 21:33:26,258: ERROR/ForkPoolWorker-2] Signal handler <function gw_task_failure at 0x7fe4541fc320> raised: ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1369, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 271, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 410, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1369, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 271, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python3.7/site-packages/girder_worker/app.py", line 187, in gw_task_failure
    _update_status(sender, JobStatus.ERROR)
  File "/usr/local/lib/python3.7/site-packages/girder_worker/utils.py", line 88, in _update_status
    task.job_manager.updateStatus(status)
  File "/usr/local/lib/python3.7/site-packages/girder_worker/utils.py", line 276, in updateStatus
    self._flush()
  File "/usr/local/lib/python3.7/site-packages/girder_worker/utils.py", line 239, in _flush
    headers=self.headers, data=data)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
[2021-02-19 21:33:26,259: ERROR/ForkPoolWorker-2] Task slicer_cli_web.girder_worker_plugin.direct_docker_run.run[7ea6058b-a05c-42bc-80c2-89228ca037fe] raised unexpected: AttributeError("'dict' object has no attribute 'exception'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1369, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 271, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 410, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1369, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 271, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/girder_worker/task.py", line 151, in __call__
    _t_kwargs = _walk_obj(kwargs, self._maybe_transform_argument)
  File "/usr/local/lib/python3.7/site-packages/girder_worker_utils/__init__.py", line 33, in _walk_obj
    for k, v in six.viewitems(obj)}
  File "/usr/local/lib/python3.7/site-packages/girder_worker_utils/__init__.py", line 33, in <dictcomp>
    for k, v in six.viewitems(obj)}
  File "/usr/local/lib/python3.7/site-packages/girder_worker_utils/__init__.py", line 36, in _walk_obj
    return [_walk_obj(v, func, leaf_condition=leaf_condition) for v in obj]
  File "/usr/local/lib/python3.7/site-packages/girder_worker_utils/__init__.py", line 36, in <listcomp>
    return [_walk_obj(v, func, leaf_condition=leaf_condition) for v in obj]
  File "/usr/local/lib/python3.7/site-packages/girder_worker_utils/__init__.py", line 41, in _walk_obj
    return func(obj)
  File "/usr/local/lib/python3.7/site-packages/girder_worker/docker/tasks/__init__.py", line 236, in _maybe_transform_argument
    arg, task=self, _default_temp_volume=self.request._default_temp_volume)
  File "/usr/local/lib/python3.7/site-packages/girder_worker/task.py", line 141, in _maybe_transform_argument
    return arg.transform(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/girder_worker/docker/transforms/girder.py", line 100, in transform
    self.gc.downloadFile(self._file_id, self._file_path)
  File "/usr/local/lib/python3.7/site-packages/girder_client/__init__.py", line 1171, in downloadFile
    fileObj = self.getFile(fileId)
  File "/usr/local/lib/python3.7/site-packages/girder_client/__init__.py", line 575, in getFile
    return self.getResource('file', fileId)
  File "/usr/local/lib/python3.7/site-packages/girder_client/__init__.py", line 519, in getResource
    return self.get(route)
  File "/usr/local/lib/python3.7/site-packages/girder_client/__init__.py", line 471, in get
    return self.sendRestRequest('GET', path, parameters, jsonResp=jsonResp)
  File "/usr/local/lib/python3.7/site-packages/girder_client/__init__.py", line 454, in sendRestRequest
    **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/slicer_cli_web/girder_worker_plugin/direct_docker_run.py", line 73, in __call__
    super(DirectDockerTask, self).__call__(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/girder_worker/docker/tasks/__init__.py", line 273, in __call__
    super(DockerTask, self).__call__(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/girder_worker/task.py", line 166, in __call__
    hook.exception()
AttributeError: 'dict' object has no attribute 'exception'
[2021-02-19 21:33:26,262: ERROR/ForkPoolWorker-2] Signal handler <function gw_task_postrun at 0x7fe45420cb90> raised: ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1369, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 271, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 410, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1369, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 271, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python3.7/site-packages/girder_worker/app.py", line 198, in gw_task_postrun
    task.job_manager._flush()
  File "/usr/local/lib/python3.7/site-packages/girder_worker/utils.py", line 239, in _flush
    headers=self.headers, data=data)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
</pre>

**Comment by manthey** [comment]
Is the rabbitmq container running?  When a task in run in HistomicsUI, the system uses celery to communicate between the girder container and the worker container (this can allow them to be on different machines).  Celery defaults to using rabbitmq as a broker, and in either the deploy_docker.py or the docker-compose methods of running DSA there should be a rabbitmq container running.

Is the girder worker url set appropriately?  That is, in Girder's plugins under the Worker, there is a setting for an "Alternative Girder API URL" that should be set to the url the worker container uses to access the girder container.  This should have been configured in either deployment method as "http://girder:8080/api/v1", which should be correct if you haven't changed how the docker network is configured in docker-compose (you can check if curling that from inside the worker container reaches the girder container).

**Comment by btsherid** [comment]
Yes, the rabbitmq container is running.

This appears to be an issue with the girder worker URL. In the web UI under the Worker plugin the Alternative Girder API URL is set to http://girder:8080/api/v1. When I do a curl from the worker container to that I get Connection reset by peer. Any ideas of how to remedy this?

root@ff79c34ae892:/# curl http://girder:8080/api/v1
curl: (56) Recv failure: Connection reset by peer

Thanks,
Brendan

**Comment by manthey** [comment]
Inside the worker container, `girder` should refer to the girder container.  If you can reach .edu:8080/api/v1 from inside the worker, you could switch to that (rather than `http://girder:8080/api/v1`), but I don't know why docker isn't allowing the worker container to reference the main girder container unless docker permissions have been restricted in some way.

**Comment by btsherid** [comment]
OK, I got a little farther. This was at least partly a firewall issue. I added the 192.168.0.0/16 to my firewall and updated my Alternative Girder API URL.

Now the worker container successfully submits the job  and spins up a new docker container. However, I'm still having an issue because I'm getting Event loop was unresponsive in Nanny and Connection closed before handshake completed.

When the new container is running I can ping 192.168.1.2 but I can't connect to it on other ports (trying using curl 192.168.1.2:port).

I believe I have updated my firewall to also allow the traffic for the new container. Is there a way I can increase the timeout? It might fix the issue but would definitely help for troubleshooting. 

Or I see that all the new container is doing is running a Python command. Is there an option to run these commands in the worker container or on the physical host?

Thanks,
Brendan

**Comment by manthey** [comment]
The event loop warnings can probably be ignored.  Some of the HistomicsTK algorithms parallelize using Dask, which, unless otherwise specified, runs just within the docker container.  If a portion of the processing takes long enough, the Dask scheduler emits those warning messages, even though everything is working -- it could theoretically miss messages from another application, but since there isn't another application using the Dask scheduler it doesn't cause any issue.

The running container doesn't necessarily expose any ports.  The containers are functionally command line programs which take input options and files and produce output files and have a standardized mechanism to report what those inputs and outputs are (using the slicer-cli specification).  Internally, algorithm containers can run anything -- the HistomicsTK container happens to all run python commands.  The HistomicsUI only provides support for running such containers; Girder Worker can run also python programs directly.

I'm not sure if you have a remaining issue.

**Comment by manthey** [comment]
Closing this.  Please reopen if it is still an issue.
