### ISSUE TITLE
AssertionError while running dsa girder docker instance.

### ISSUE THREAD

**Issue by rashidpokkat** [DigitalSlideArchive/digital_slide_archive#282]
Im getting the below error when I'm trying to run the docker instance of dsa girder

```
Running in mode: production
Connecting to MongoDB: mongodb://mongodb:27017/girder?authSource=admin
Loaded plugin "homepage"
Loaded plugin "jobs"
Loaded plugin "ldap"
Loaded plugin "resource_path_tools"
Loaded plugin "user_quota"
Loaded plugin "virtual_folders"
Loaded plugin "girder_xtk_demo"
Loaded plugin "worker"
Loaded plugin "import_tracker"
Loaded plugin "slicer_cli_web"
Loaded tile source vips
Loaded tile source tiff
Loaded tile source test
Loaded tile source pil
Loaded tile source openslide
Loaded tile source openjpeg
Loaded tile source gdal
Loaded tile source deepzoom
Loaded tile source rasterio
Loaded tile source ometiff
Loaded tile source multi
Loaded tile source mapnik
Loaded tile source dicom
Loaded tile source tifffile
Loaded tile source bioformats
Loaded tile source nd2
Loaded plugin "large_image"
Traceback (most recent call last):
  File "/opt/digital_slide_archive/devops/dsa/provision.py", line 425, in <module>
    configureServer()
  File "/opt/girder/girder/utility/server.py", line 94, in configureServer
    plugin._loadPlugins(info, plugins)
  File "/opt/girder/girder/plugin.py", line 206, in _loadPlugins
    pluginObject.load(info)
  File "/opt/girder/girder/plugin.py", line 58, in wrapper
    self._return = func(self, *args, **kwargs)
  File "/opt/large_image/girder_annotation/girder_large_image_annotation/__init__.py", line 88, in load
    Annotation()._migrateDatabase()
  File "/opt/large_image/girder_annotation/girder_large_image_annotation/models/annotation.py", line 727, in _migrateDatabase
    self._migrateACL(annotation)
  File "/opt/large_image/girder_annotation/girder_large_image_annotation/models/annotation.py", line 767, in _migrateACL
    self.setPublic(annotation, folder.get('public'), save=False)
  File "/opt/girder/girder/models/model_base.py", line 993, in setPublic
    assert isinstance(public, bool)
AssertionError
```

It would be great if anybody can suggest me what to do to resolve this. Thank you.

**Comment by manthey** [comment]
Are you updating an old version?  I think this is trying to update an old database entry to ensure it complies with the current schema.  If that is the case, then some upgrade path isn't tested, and we can add a guard for this in girder_large_image_annotation.

**Comment by manthey** [comment]
Can you try again?  I added a guard here https://github.com/girder/large_image/pull/1243.  Please reopen if this is still an issue.
