### ISSUE TITLE
girder Errors on clean install

### ISSUE THREAD

**Issue by MartinKlefas** [DigitalSlideArchive/digital_slide_archive#317]
I started a new install on aws to try to scale up a bit, and unfortunately there seem to be some issues. Perhaps there's a step missing in the install instructions or something?

The error log was:

irder_1     | Traceback (most recent call last):
girder_1     |   File "/opt/digital_slide_archive/devops/dsa/provision.py", line 686, in <module>
girder_1     |     configureServer()
girder_1     |   File "/opt/girder/girder/utility/server.py", line 79, in configureServer
girder_1     |     api_main.addApiToNode(root)
girder_1     |   File "/opt/girder/girder/api/api_main.py", line 19, in addApiToNode
girder_1     |     _addV1ToNode(node.api)
girder_1     |   File "/opt/girder/girder/api/api_main.py", line 29, in _addV1ToNode
girder_1     |     node.v1.assetstore = assetstore.Assetstore()
girder_1     |   File "/opt/girder/girder/api/v1/assetstore.py", line 22, in __init__
girder_1     |     self._model = AssetstoreModel()
girder_1     |   File "/opt/girder/girder/models/model_base.py", line 75, in __call__
girder_1     |     cls._instance = super().__call__(*args, **kwargs)
girder_1     |   File "/opt/girder/girder/models/model_base.py", line 108, in __init__
girder_1     |     self.reconnect()
girder_1     |   File "/opt/girder/girder/models/model_base.py", line 115, in reconnect
girder_1     |     db_connection = getDbConnection()
girder_1     |   File "/opt/girder/girder/models/__init__.py", line 96, in getDbConnection
girder_1     |     client.server_info()
girder_1     |   File "/opt/venv/lib/python3.9/site-packages/pymongo/mongo_client.py", line 2086, in server_info
girder_1     |     return self.admin.command(
girder_1     |   File "/opt/venv/lib/python3.9/site-packages/pymongo/database.py", line 827, in command
girder_1     |     with self.__client._socket_for_reads(read_preference, session) as (sock_info, secondary_ok):
girder_1     |   File "/.pyenv/versions/3.9.18/lib/python3.9/contextlib.py", line 119, in __enter__
girder_1     |     return next(self.gen)
girder_1     |   File "/opt/venv/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1478, in _socket_for_reads
girder_1     |     server = self._select_server(read_preference, session)
girder_1     |   File "/opt/venv/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1436, in _select_server
girder_1     |     server = topology.select_server(server_selector)
girder_1     |   File "/opt/venv/lib/python3.9/site-packages/pymongo/topology.py", line 250, in select_server
girder_1     |     return random.choice(self.select_servers(selector, server_selection_timeout, address))
girder_1     |   File "/opt/venv/lib/python3.9/site-packages/pymongo/topology.py", line 211, in select_servers
girder_1     |     server_descriptions = self._select_servers_loop(selector, server_timeout, address)
girder_1     |   File "/opt/venv/lib/python3.9/site-packages/pymongo/topology.py", line 226, in _select_servers_loop
girder_1     |     raise ServerSelectionTimeoutError(
girder_1     | pymongo.errors.ServerSelectionTimeoutError: mongodb:27017: [Errno -2] Name or service not known, Timeout: 20.0s, Topology Description: <TopologyDescription id: 65c55dd5bfb65fac39fee54b, topology_type: Single, servers: [<ServerDescription ('mongodb', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongodb:27017: [Errno -2] Name or service not known')>]>
dsa_girder_1 exited with code 1

It kept looping round trying to start girder and failing

**Comment by manthey** [comment]
This is saying the mongodb is failing to start.  What does the mongo container show (`docker logs -f dsa-mongo-1` might be the command to show this).
